server:
  port: 8761                #指定该Eureka实例的端口

spring:
  application:
    name: eureka-server     #服务名称,自定义
  #security:
    #user:
      #name: user            #配置BASIC认证登录的账号
      #password: 123456      #配置BASIC认证登录的密码

eureka:
  instance:
    #hostname: eureka8761        #eureka服务端所在的服务器域名
    hostname: localhost
  client:
    registerWithEureka: false     #禁止注册自身
    fetchRegistry: false          #因为该服务没有注册到其他注册中心，所以关闭从注册中心拉取服务列表。
    serviceUrl:
      #defaultZone: http://user:123456@localhost:8080/eureka/  #服务注册中心地址，http://账号:密码@主机名称:端口/Eureka/
      #defaultZone: http://localhost:8761/eureka/  #多eureka服务，配置其他节点（即8052）
      #defaultZone: http://eureka8762.com:8762/eureka/  #多eureka服务，配置其他节点（即8052）
      defaultZone: http://eureka.klfront.com:8761/eureka/
  server:
    renewalPercentThreshold: 0.49    #设置心跳正常的阀值，默认为1，测试时可以调低
